import { axios, apiURL } from './config.js';

class Order {
    static async getAllSalesmanOrder(id, page = 1) {
        try {
            const response = await axios.get(`${apiURL}/order/all/salesman/${id}?page=${page}`);
            return response.data;
        } catch (error) {
            if(error.response && error.response.data)
                return error.response.data
            else return {success: false, message: 'Houve um erro desconhecido'};
        }
    }

    static async getAllClientOrder(id, page = 1) {
        try {
            const response = await axios.get(`${apiURL}/order/all/client/${id}?page=${page}`);
            return response.data;
        } catch (error) {
            if(error.response && error.response.data)
                return error.response.data
            else return {success: false, message: 'Houve um erro desconhecido'};
        }
    }

    static async getOrderById(id) {
        try {
            const response = await axios.get(`${apiURL}/order/${id}`);
            return response.data;
        } catch (error) {
            if(error.response && error.response.data)
                return error.response.data
            else return {success: false, message: 'Houve um erro desconhecido'};
        }
    }
    static async create(data) {
        try {
            const response = await axios.post(`${apiURL}/order`, data);
            return response.data;
        } catch (error) {
            if(error.response && error.response.data)
                return error.response.data
            else return {success: false, message: 'Houve um erro desconhecido'};
        }
    }
    static async update(id, data) {
        try {
            const response = await axios.put(`${apiURL}/category/${id}`, data);
            return response.data;
        } catch (error) {
            if(error.response && error.response.data)
                return error.response.data
            else return {success: false, message: 'Houve um erro desconhecido'};
        }
    }

    static async destroy(id) {
        try {
            const response = await axios.delete(`${apiURL}/category/${id}`);
            return response.data;
        } catch (error) {
            if(error.response && error.response.data)
                return error.response.data
            else return {success: false, message: 'Houve um erro desconhecido'};
        }
    }
}

export default Order